# Generated by Django 5.1.3 on 2024-11-14 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_is_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cretead_at',
            new_name='created_at',
        ),
    ]
