# Generated by Django 5.1.3 on 2024-11-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='website',
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
