# Generated by Django 5.1.3 on 2024-11-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_contact_website_contact_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_solved',
            field=models.BooleanField(default=True),
        ),
    ]
